### ISSUE TITLE
如何把监听的地址改为127.0.0.1？

### ISSUE THREAD

**Issue by luckypoem** [crabkun/go-https-proxy#1]
hi.

[root@host go-https-proxy-by-crabkun]# ./go-https-proxy-by-crabkun
2019/08/20 15:59:16 listen at [::]:9070

谢谢

**Comment by crabkun** [comment]
你好
把代码里面的
`net.Listen("tcp",":8080")`
改为
`net.Listen("tcp","127.0.0.1:8080")`
